teams = {	"CHI":"Chicago Bulls",
			 "ATL":"Atlanta Hawks", 
			 "CLE":"Cleveland Cavaliers", 
			 "DET":"Detroit Pistons", 
			 "CHA":"Charlotte Hornets", 
			 "IND":"Indiana Pacers", 
			 "BOS":"Boston Celtics", 
			 "MIA":"Miami Heat", 
			 "NYK":"New York Knicks", 
			 "ORL":"Orlando Magic", 
			 "TOR":"Toronto Raptors", 
			 "WAS":"Washington Wizards", 
			 "MIL":"Milwaukee Bucks", 
			 "BRK":"Brooklyn Nets", 
			 "PHI":"Philadelphia 76ers", 
			 "GSW":"Golden State Warriors", 
			 "SAS":"San Antonio Spurs", 
			 "DAL":"Dallas Mavericks", 
			 "LAC":"Los Angeles Clippers", 
			 "MEM":"Memphis Grizzlies", 
			 "OKC":"Oklahoma City Thunder", 
			 "UTA":"Utah Jazz", 
			 "DEN":"Denver Nuggets", 
			 "PHO":"Phoenix Suns",
			 "HOU":"Houston Rockets", 
			 "MIN":"Minnesota Timberwolves", 
			 "POR":"Portland Trail Blazers", 
			 "SAC":"Sacramento Kings", 
			 "LAL":"Los Angeles Lakers", 
			 "NOP":"New Orleans Pelicans",
			 "CHA":"Charlotte Hornets/Bobcats",
			 "VAN":"Vancouver Grizzlies",
			 "NOH":"New Orleans Hornets",
			 "NOK":"New Orleans/Oklahoma City Hornets",
			 "SEA":"Seattle SuperSonics",
			 "NJN":"New Jersey Nets"
		}